name: freditor
favicon: null
layout_spectrum: 0.76463
typography_spectrum: 0.75342
title: Fred Beahm
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#ababab'
    - '#656565'
    - '#003e7b'
  brandStrength: 0.5
  lightness: 0.8381294144783169
  saturation: 0.3363413189072162
  rhythmicContrast: 0.05232358886860311
purpose: []
